server:
  port: 8085
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/template/
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    servlet:
      content-type: text/html
#忽略权限拦截(在密码模式时为false，验证码code模式是true(没有结合数据库之前这样写，增加数据库配置后这一步去掉))
#security:
#  basic:
#    enabled: false
#  user:
#    name: admin
#    password: 123456